### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by jamesladd** [brillout/vuetify3-ssr#1]
Hey Brillout,

Thank you for looking into Vite with Vuetify3 and SSR.

Just the thing I was trying to do and have hit the same issues as you.
https://github.com/vuetifyjs/vuetify/issues/13936

Please let me know if I can help you but I think your fu is way better than mine.
I'll see if I can find anything elsewhere that might help.

**Comment by brillout** [comment]
Would be great to get this example working.

Did you manage to use vite(-plugin-ssr) with Vuetify?

**Comment by jamesladd** [comment]
Updating Vuetify to "vuetify": "^3.0.0-alpha.10",
and importing the ".mjs" files appeared to do the trick with your vuetify3-ssr repo.

**Comment by brillout** [comment]
Indeed. Thanks.
