### ISSUE TITLE
Same functionality with vuetify 2. 

### ISSUE THREAD

**Issue by farid-temuri-lofty** [brillout/vuetify3-ssr#2]
Is it possible to do the same with vuetfy 2.x? Since it has vite support (I'm trying myself, but getting errors
```js
export * from './components';
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:352:18)
```

both with vite-plugin-ssr and plain vite v3+ features.

**Comment by brillout** [comment]
I don't think it's related to vite-plugin-ssr.

(Also please read https://brillout.github.io/rules/, thanks!)
